/* DO NOT MODIFY THIS FILE!  It was generated by "charset.pl".  */

/* Conversion of files between different charsets and usages.
   Copyright (C) 1990, 1993 Free Software Foundation, Inc.
   Francois Pinard <pinard@iro.umontreal.ca>, 1993.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#include "recode.h"

/* ISO_646.basic:1983
   ref
*/

static DOUBLE_TABLE table_0 = 
  {
    NULL,
    "SP! \"     % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z         _ ",
    "  a b c d e f g h i j k l m n o p q r s t u v w x y z           ",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* INVARIANT
*/

static DOUBLE_TABLE table_1 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \"     % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z         _ ",
    "  a b c d e f g h i j k l m n o p q r s t u v w x y z         DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_646.irv:1983
   iso-ir-2
   irv
*/

static DOUBLE_TABLE table_2 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* BS_4730
   iso-ir-4
   ISO646-GB
   gb
   uk
*/

static DOUBLE_TABLE table_3 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ANSI_X3.4-1968
   iso-ir-6
   ANSI_X3.4-1986
   ISO_646.irv:1991
   ASCII
   ISO646-US
   US-ASCII
   us
   IBM367
   cp367
*/

static DOUBLE_TABLE table_4 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NATS-SEFI
   iso-ir-8-1
*/

static DOUBLE_TABLE table_5 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "UAA B C D E F G H I J K L M N O P Q R S T U V W X Y Z A:O:AAfS_ ",
    "UBa b c d e f g h i j k l m n o p q r s t u v w x y z a:o:aa-NDT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NATS-SEFI-ADD
   iso-ir-8-2
*/

static DOUBLE_TABLE table_6 = 
  {
    NULL,
    NULL,
    "  A!    D/E'                    TH        U:          AEO/      ",
    "  a!    d/e'                    th        u:          aeo/      ",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NATS-DANO
   iso-ir-9-1
*/

static DOUBLE_TABLE table_7 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! <<>>DO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "UAA B C D E F G H I J K L M N O P Q R S T U V W X Y Z AEO/AAfS_ ",
    "UBa b c d e f g h i j k l m n o p q r s t u v w x y z aeo/aa-NDT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NATS-DANO-ADD
   iso-ir-9-2
*/

static DOUBLE_TABLE table_8 = 
  {
    NULL,
    NULL,
    "  A!    D/E'                    TH        U:          A:O:      ",
    "  a!    d/e'                    th        u:          a:o:      ",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* SEN_850200_B
   iso-ir-10
   FI
   ISO646-FI
   ISO646-SE
   se
*/

static DOUBLE_TABLE table_9 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z A:O:AA'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z a:o:aa'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* SEN_850200_C
   iso-ir-11
   ISO646-SE2
   se2
*/

static DOUBLE_TABLE table_10 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "E'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A:O:AAU:_ ",
    "e'a b c d e f g h i j k l m n o p q r s t u v w x y z a:o:aau:DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6220-1969-jp
   JIS_C6220-1969
   iso-ir-13
   katakana
   x0201-7
*/

static DOUBLE_TABLE table_11 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP._<'>',_.6Woa6i6u6e6o6YAYUYOTU-6A6I6U6E6O6KaKiKuKeKoSaSiSuSeSo",
    "TaTiTuTeToNaNiNuNeNoHaHiHuHeHoMaMiMuMeMoYaYuYoRaRiRuReRoWaN6\"505",
    "                                                              DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6220-1969-ro
   iso-ir-14
   jp
   ISO646-JP
*/

static DOUBLE_TABLE table_12 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(Ye)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* IT
   iso-ir-15
   ISO646-IT
*/

static DOUBLE_TABLE table_13 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "SEA B C D E F G H I J K L M N O P Q R S T U V W X Y Z DGc,e''>_ ",
    "u!a b c d e f g h i j k l m n o p q r s t u v w x y z a!o!e!i!DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* PT
   iso-ir-16
   ISO646-PT
*/

static DOUBLE_TABLE table_14 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "SEA B C D E F G H I J K L M N O P Q R S T U V W X Y Z A?C,O?'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z a?c,o?DGDT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ES
   iso-ir-17
   ISO646-ES
*/

static DOUBLE_TABLE table_15 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "SEA B C D E F G H I J K L M N O P Q R S T U V W X Y Z !IN??I'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z DGn?c,'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* greek7-old
   iso-ir-18
*/

static DOUBLE_TABLE table_16 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "''a*b*q*d*e*f*g*y*i*c*k*l*m*n*o*p*j3r*s*t*h*w**sx*u*z*?,,,,''?_ ",
    "'!A*B*Q*D*E*F*G*Y*I*C*K*L*M*N*O*P*  R*S*T*H*W*.MX*U*Z*?;;;;'':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* latin-greek
   iso-ir-19
*/

static DOUBLE_TABLE table_17 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!A*B*Q*D*E*F*G*Y*I*C*K*L*M*N*O*P*  R*S*T*H*W*.MX*U*Z*(!!!!)':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* DIN_66003
   iso-ir-21
   de
   ISO646-DE
*/

static DOUBLE_TABLE table_18 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "SEA B C D E F G H I J K L M N O P Q R S T U V W X Y Z A:O:U:'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z a:o:u:ssDT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NF_Z_62-010_(1973)
   iso-ir-25
   ISO646-FR1
*/

static DOUBLE_TABLE table_19 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "a!A B C D E F G H I J K L M N O P Q R S T U V W X Y Z DGc,SE'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z e'u!e!':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* Latin-greek-1
   iso-ir-27
*/

static DOUBLE_TABLE table_20 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SPC*\" G*Cu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 Q*; < = > P*",
    "D*A B C D E F G H I J K L M N O P Q R S T U V W X Y Z W*H*F*L*S*",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_5427
   iso-ir-37
*/

static DOUBLE_TABLE table_21 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "jua=b=c=d=e=f=g=h=i=j=k=l=m=n=o=p=jar=s=t=u=z%v=%'y=z=s%jescc%='",
    "JUA=B=C=D=E=F=G=H=I=J=K=L=M=N=O=P=JAR=S=T=U=Z%V=%\"Y=Z=S%JEScC%DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* BS_viewdata
   iso-ir-47
*/

static DOUBLE_TABLE table_22 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <-12->-!OS",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z 14PP34-:DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* INIS
   iso-ir-49
*/

static DOUBLE_TABLE table_23 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP      DO%   ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = >   ",
    "  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(  )>    ",
    "  a b c d e f g h i j k l m n o p q r s t u v w x y z   !!    DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* INIS-8
   iso-ir-50
*/

static DOUBLE_TABLE table_24 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP                                                  a*b*g*d*C*  ",
    "                                                            ->In",
    "0S1S2S3S4S5S6S7S8S9S+S-SRuD*L*W*0s1s2s3s4s5s6s7s8s9sS*m*n*w*p*DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* INIS-cyrillic
   iso-ir-51
*/

static DOUBLE_TABLE table_25 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP                      RT  ->Ina*b*g*d*S*m*n*w*p*C*D*L*W*=\"-S+S",
    "jua=b=c=d=e=f=g=h=i=j=k=l=m=n=o=p=jar=s=t=u=z%v=%'y=z=s%jescc%='",
    "JUA=B=C=D=E=F=G=H=I=J=K=L=M=N=O=P=JAR=S=T=U=Z%V=%\"Y=Z=S%JEScC%DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_5427:1981
   iso-ir-54
*/

static DOUBLE_TABLE table_26 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP                                                              ",
    "g3d%g%ieiodsiiyij%ljnjtskjv%dz  y3f3v3o3              <(  )>  _ ",
    "G3D%G%IEIODSIIYIJ%LJNJTsKJV%DZ=\"Y3F3V3O3                      DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_5428:1980
   iso-ir-55
*/

static DOUBLE_TABLE table_27 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP\"!\"'\":\"?\"p\"d\"i                <<>>\"9\"6'G,G          .M      ; ",
    "  A*B*  G*D*E*T3M3Z*Y*H*I*K*L*M*N*C*O*P*K3R*S*  T*U*F*X*Q*W*P3  ",
    "  a*b*b3g*d*e*t3m3z*y*h*i*k*l*m*n*c*o*p*k3r*s**st*u*f*x*q*w*p3DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* GB_1988-80
   iso-ir-57
   cn
   ISO646-CN
*/

static DOUBLE_TABLE table_28 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbYe% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NS_4551-1
   iso-ir-60
   ISO646-NO
   no
*/

static DOUBLE_TABLE table_29 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z AEO/AA'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z aeo/aa'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NS_4551-2
   ISO646-NO2
   iso-ir-61
   no2
*/

static DOUBLE_TABLE table_30 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PIDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z AEO/AA'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z aeo/aa!!DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NF_Z_62-010
   iso-ir-69
   ISO646-FR
   fr
*/

static DOUBLE_TABLE table_31 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "a!A B C D E F G H I J K L M N O P Q R S T U V W X Y Z DGc,SE'>_ ",
    "Mya b c d e f g h i j k l m n o p q r s t u v w x y z e'u!e!':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* PT2
   iso-ir-84
   ISO646-PT2
*/

static DOUBLE_TABLE table_32 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "''A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A?C,O?'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z a?c,o?'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ES2
   iso-ir-85
   ISO646-ES2
*/

static DOUBLE_TABLE table_33 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "SbA B C D E F G H I J K L M N O P Q R S T U V W X Y Z !IN?C,?I_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z ''n?c,':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* MSZ_7795.3
   iso-ir-86
   ISO646-HU
   hu
*/

static DOUBLE_TABLE table_34 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "A'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z E'O:U:'>_ ",
    "a'a b c d e f g h i j k l m n o p q r s t u v w x y z e'o:u:'\"DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* greek7
   iso-ir-88
*/

static DOUBLE_TABLE table_35 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA*B*G*D*E*Z*Y*H*I*  K*L*M*N*C*O*P*R*S*T*U*F*  X*Q*W*<(//)>'>_ ",
    "'!a*b*g*d*e*z*y*h*i*  k*l*m*n*c*o*p*r*s*t*u*f**sx*q*w*(!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ASMO_449
   ISO_9036
   arabic7
   iso-ir-89
*/

static DOUBLE_TABLE table_36 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + ,+- . / 0 1 2 3 4 5 6 7 8 9 : ;+< = > ?+",
    "AtH'aMaHwHahyHa+b+tmt+tkg+hkx+d+dkr+z+s+snc+ddtjzHe+i+<(//)>'>_ ",
    "++f+q+k+l+m+n+h+w+j+y+:+\"+=+/+'+1+3+0+                (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-a
   iso-ir-91
   jp-ocr-a
*/

static DOUBLE_TABLE table_37 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP  \" PdDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; 1h= 3h? ",
    "  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z   Ye2h'>_ ",
    "                                                        4h    DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-b
   iso-ir-92
   ISO646-JP-OCR-B
   jp-ocr-b
*/

static DOUBLE_TABLE table_38 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z </Ye/>'>_ ",
    "  a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)  DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-b-add
   iso-ir-93
   jp-ocr-b-add
*/

static DOUBLE_TABLE table_39 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP    PdCu//  SE                                                ",
    NULL,
    "                                                              DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-hand
   iso-ir-94
   jp-ocr-hand
*/

static DOUBLE_TABLE table_40 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z </Ye/>'>_ ",
    "                                                        !!    DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-hand-add
   iso-ir-95
   jp-ocr-hand-add
*/

static DOUBLE_TABLE table_41 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP        //                                                    ",
    NULL,
    "                                                              DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_C6229-1984-kana
   iso-ir-96
*/

static DOUBLE_TABLE table_42 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP  <'>'    Wo                  -6A6I6U6E6O6KaKiKuKeKoSaSiSuSeSo",
    "TaTiTuTeToNaNiNuNeNoHaHiHuHeHoMaMiMuMeMoYaYuYoRaRiRuReRoWaN6\"505",
    "                                                              DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_2033-1983
   iso-ir-98
   e13b
*/

static DOUBLE_TABLE table_43 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP                              0 1 2 3 4 5 6 7 8 9 1j2j3j4j    ",
    NULL,
    "                                                              DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_8859-1:1987
   iso-ir-100
   ISO_8859-1
   ISO-8859-1
   latin1
   l1
   IBM819
   CP819
*/

static DOUBLE_TABLE table_44 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS!ICtPdCuYeBBSE':Co-a<<NO--Rg'-DG+-2S3S''MyPI.M',1S-o>>141234?I",
    "A!A'A>A?A:AAAEC,E!E'E>E:I!I'I>I:D-N?O!O'O>O?O:*XO/U!U'U>U:Y'THss",
    "a!a'a>a?a:aaaec,e!e'e>e:i!i'i>i:d-n?o!o'o>o?o:-:o/u!u'u>u:y'thy:",
  };

/* ISO_8859-2:1987
   iso-ir-101
   ISO_8859-2
   ISO-8859-2
   latin2
   l2
*/

static DOUBLE_TABLE table_45 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSA;'(L/CuL<S'SE':S<S,T<Z'--Z<Z.DGa;';l/''l<s''<',s<s,t<z''\"z<z.",
    "R'A'A>A(A:L'C'C,C<E'E;E:E<I'I>D<D/N'N<O'O>O\"O:*XR<U0U'U\"U:Y'T,ss",
    "r'a'a>a(a:l'c'c,c<e'e;e:e<i'i>d<d/n'n<o'o>o\"o:-:r<u0u'u\"u:y't,'.",
  };

/* T.61-7bit
   iso-ir-102
*/

static DOUBLE_TABLE table_46 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(  )>  _ ",
    "  a b c d e f g h i j k l m n o p q r s t u v w x y z   !!    DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_8859-3:1988
   iso-ir-109
   ISO_8859-3
   ISO-8859-3
   latin3
   l3
*/

static DOUBLE_TABLE table_47 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSH/'(PdCu  H>SE':I.S,G(J>--  Z.DGh/2S3S''Myh>.M',i.s,g(j>12  z.",
    "A!A'A>  A:C.C>C,E!E'E>E:I!I'I>I:  N?O!O'O>G.O:*XG>U!U'U>U:U(S>ss",
    "a!a'a>  a:c.c>c,e!e'e>e:i!i'i>i:  n?o!o'o>g.o:-:g>u!u'u>u:u(s>'.",
  };

/* ISO_8859-4:1988
   iso-ir-110
   ISO_8859-4
   ISO-8859-4
   latin4
   l4
*/

static DOUBLE_TABLE table_48 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSA;kkR,CuI?L,SE':S<E-G,T/--Z<'-DGa;';r,''i?l,'<',s<e-g,t/NGz<ng",
    "A-A'A>A?A:AAAEI;C<E'E;E:E.I'I>I-D/N,O-K,O>O?O:*XO/U;U'U>U:U?U-ss",
    "a-a'a>a?a:aaaei;c<e'e;e:e.i'i>i-d/n,o-k,o>o?o:-:o/u;u'u>u:u?u-'.",
  };

/* ECMA-cyrillic
   iso-ir-111
*/

static DOUBLE_TABLE table_49 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSIOD%G%IEDSIIYIJ%LJNJTsKJ--V%DZN0iod%g%iedsiiyij%ljnjtskjCuv%dz",
    "A=B=V=G=D=E=Z%Z=I=J=K=L=M=N=O=P=R=S=T=U=F=H=C=C%S%Sc=\"Y=%\"JEJUJA",
    "a=b=v=g=d=e=z%z=i=j=k=l=m=n=o=p=r=s=t=u=f=h=c=c%s%sc='y=%'jejuja",
  };

/* CSA_Z243.4-1985-1
   iso-ir-121
   ISO646-CA
   csa7-1
   ca
*/

static DOUBLE_TABLE table_50 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "a!A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a>c,e>i>_ ",
    "o>a b c d e f g h i j k l m n o p q r s t u v w x y z e'u!e!u>DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* CSA_Z243.4-1985-2
   iso-ir-122
   ISO646-CA2
   csa7-2
*/

static DOUBLE_TABLE table_51 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "a!A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a>c,e>E'_ ",
    "o>a b c d e f g h i j k l m n o p q r s t u v w x y z e'u!e!u>DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* CSA_Z243.4-1985-gr
   iso-ir-123
*/

static DOUBLE_TABLE table_52 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS!I':PdCtYe+-''(S)S12+S',--.M-S0S1S2S3S4S5S6S7S8S9S1434<=!=>=?I",
    "A!A'A>C,E!E'E>E:I'I>I:N?O'O>U!U'U>U:RgSEPIm*-a-o'6'9\"6\"9<<>>DGBB",
    "a!a'a>c,e!e'e>e:i'i>i:n?o'o>u!u'u>u:CohhvvuruldldrvruhvldhvhNOFB",
  };

/* ISO_8859-7:1987
   iso-ir-126
   ISO_8859-7
   ISO-8859-7
   ELOT_928
   ECMA-118
   greek
   greek8
*/

static DOUBLE_TABLE table_53 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS9''9Pd    BBSE':Co  <<NO--  -MDG+-2S3S'''%A%.ME%Y%I%>>O%12U%W%",
    "i3A*B*G*D*E*Z*Y*H*I*K*L*M*N*C*O*P*R*  S*T*U*F*X*Q*W*J*V*a%e%y%i%",
    "u3a*b*g*d*e*z*y*h*i*k*l*m*n*c*o*p*r**ss*t*u*f*x*q*w*j*v*o%u%w%  ",
  };

/* ISO_8859-6:1987
   iso-ir-127
   ISO_8859-6
   ISO-8859-6
   ECMA-114
   ASMO-708
   arabic
*/

static DOUBLE_TABLE table_54 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS      Cu              ,+--                          ;+      ?+",
    "  H'aMaHwHahyHa+b+tmt+tkg+hkx+d+dkr+z+s+snc+ddtjzHe+i+          ",
    "++f+q+k+l+m+n+h+w+j+y+:+\"+=+/+'+1+3+0+                          ",
  };

/* ISO_8859-8:1988
   iso-ir-138
   ISO_8859-8
   ISO-8859-8
   hebrew
*/

static DOUBLE_TABLE table_55 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS  CtPdCuYeBBSE':Co*X<<NO--Rg'-DG+-2S3S''MyPI.M',1S-:>>141234  ",
    "                                                              =2",
    "A+B+G+D+H+W+Z+X+TjJ+K%K+L+M%M+N%N+S+E+P%P+ZjZJQ+R+ShT+          ",
  };

/* CSN_369103
   iso-ir-139
*/

static DOUBLE_TABLE table_56 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSA;'(L/DOL<S'SE':S<S,T<Z'--Z<Z.DGa;';l/''l<s''<',s<s,t<z''\"z<z.",
    "R'A'A>A(A:L'C'C,C<E'E;E:E<I'I>D<D/N'N<O'O>O\"O:*XR<U0U'U\"U:Y'T,ss",
    "r'a'a>a(a:l'c'c,c<e'e;e:e<i'i>d<d/n'n<o'o>o\"o:-:r<u0u'u\"u:y't,'.",
  };

/* JUS_I.B1.002
   iso-ir-141
   ISO646-YU
   js
   yu
*/

static DOUBLE_TABLE table_57 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "Z<A B C D E F G H I J K L M N O P Q R S T U V W X Y Z S<D/C'C<_ ",
    "z<a b c d e f g h i j k l m n o p q r s t u v w x y z s<d/c'c<DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* IEC_P27-1
   iso-ir-143
*/

static DOUBLE_TABLE table_58 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "'<=3ANOR(U)U(C)C<==>.::.(--)(_)_InIo00NBdP?1?2?-?==<!=>=<>NOFATE",
    "A+OSPPG*D*-T-V-LH*<//>L*1'2'C*-+P*2SS**X3SU*F*.MQ*W*/0>VRTf(0(+-",
    "DGa*b*g*d*e*z*y*h*i*k*l*m*n*c*%0p*r*s*-:t*u*f*x*q*w*/-<--!->-v'-",
  };

/* ISO_8859-5:1988
   iso-ir-144
   ISO_8859-5
   ISO-8859-5
   cyrillic
*/

static DOUBLE_TABLE table_59 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSIOD%G%IEDSIIYIJ%LJNJTsKJ--V%DZA=B=V=G=D=E=Z%Z=I=J=K=L=M=N=O=P=",
    "R=S=T=U=F=H=C=C%S%Sc=\"Y=%\"JEJUJAa=b=v=g=d=e=z%z=i=j=k=l=m=n=o=p=",
    "r=s=t=u=f=h=c=c%s%sc='y=%'jejujaN0iod%g%iedsiiyij%ljnjtskjSEv%dz",
  };

/* JUS_I.B1.003-serb
   iso-ir-146
   serbian
*/

static DOUBLE_TABLE table_60 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "Z%A=B=C=D=E=F=G=H=I=J%K=L=M=N=O=P=LJR=S=T=U=V=NJDZDSZ=S%D%TsC%_ ",
    "z%a=b=c=d=e=f=g=h=i=j%k=l=m=n=o=p=ljr=s=t=u=v=njdzdsz=s%d%tsc%DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JUS_I.B1.003-mac
   macedonian
   iso-ir-147
*/

static DOUBLE_TABLE table_61 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "Z%A=B=C=D=E=F=G=H=I=J%K=L=M=N=O=P=LJR=S=T=U=V=NJDZDSZ=S%G%KJC%_ ",
    "z%a=b=c=d=e=f=g=h=i=j%k=l=m=n=o=p=ljr=s=t=u=v=njdzdsz=s%g%kjc%DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_8859-9:1989
   iso-ir-148
   ISO_8859-9
   ISO-8859-9
   latin5
   l5
*/

static DOUBLE_TABLE table_62 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS!ICtPdCuYeBBSE':Co-a<<NO--Rg'-DG+-2S3S''MyPI.M',1S-o>>141234?I",
    "A!A'A>A?A:AAAEC,E!E'E>E:I!I'I>I:G(N?O!O'O>O?O:*XO/U!U'U>U:I.S,ss",
    "a!a'a>a?a:aaaec,e!e'e;e:e.i'i>i-g(n?o!o'o>o?o:-:o/u!u'u>u:i.s,y:",
  };

/* greek-ccitt
   iso-ir-150
*/

static DOUBLE_TABLE table_63 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA*B*G*D*E*Z*Y*H*I*K*L*M*N*C*O*P*R*  S*T*U*F*X*Q*W*  <(//)>'>_ ",
    "  a*b*g*d*e*z*y*h*i*k*l*m*n*c*o*p*r**ss*t*u*f*x*q*w*  (!!!!)'-DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* NC_NC00-10:81
   cuba
   iso-ir-151
   ISO646-CU
*/

static DOUBLE_TABLE table_64 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z !IN?)>?I_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z ''n?<(':DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* ISO_6937-2-25
   iso-ir-152
*/

static DOUBLE_TABLE table_65 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbCu% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS                  \"6  <--!->-v                    \"9          ",
    "                                        TMMd            18385878",
    "Om          IJL.    OE  W>Y>Y:'n            ijl.    oe  w>y>    ",
  };

/* GOST_19768-74
   ST_SEV_358-88
   iso-ir-153
*/

static DOUBLE_TABLE table_66 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSIO                      --    A=B=V=G=D=E=Z%Z=I=J=K=L=M=N=O=P=",
    "R=S=T=U=F=H=C=C%S%Sc=\"Y=%\"JEJUJAa=b=v=g=d=e=z%z=i=j=k=l=m=n=o=p=",
    "r=s=t=u=f=h=c=c%s%sc='y=%'jejuja  io                            ",
  };

/* ISO_8859-supp
   iso-ir-154
   latin1-2-5
*/

static DOUBLE_TABLE table_67 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "    A-C>C.  E.E-G>'6\"6TM<--!->-v    a-c>c.d-e.e-g>'9\"9Md18385878",
    "  G(G.G,H>H/I?I.I-I;IJJ>K,L,L.N,-MNGO-OER,S>T/THU?U(U-U;W>Y'Y>Y:",
    "Omg(g.g,h>h/i?i.i-i;ijj>k,l,l.n,kkngo-oer,s>t/thu?u(u-u;w>y'y>'n",
  };

/* ISO_10367-box
   iso-ir-155
*/

static DOUBLE_TABLE table_68 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    NULL,
    "VVHHDRLDURULVRVLDHUHVHUBLBFBsB  vvhhdrdlurulvrvldhuhvh.S:S?S    ",
    NULL,
  };

/* latin6
   iso-ir-157
   l6
*/

static DOUBLE_TABLE table_69 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSA;E-G,I-I?K,L,N'R,S<T/Z<--kkNGd/a;e-g,i-i?k,l,n'r,s<t/z<SEssng",
    "A-A'A>A?A:AAAEI;C<E'E;E:E.I'I>I:D/N,O-O'O>O?O:U?O/U;U'U>U:Y'THU-",
    "a-a'a>a?a:aaaei;c<e'e;e:e.i'i>i:d-n,o-o'o>o?o:u?o/u;u'u>u:y'thu-",
  };

/* latin-lap
   lap
   iso-ir-158
*/

static DOUBLE_TABLE table_70 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "''                              ;S                              ",
    "A(A>A!A-A1A7A3E(E!E-G/G<K<O(O!O;O1U-EDEZ                        ",
    "a(a>a!a-a1a7a3e(e!e-g/g<k<o(o!o;o1u-edez                        ",
  };

/* DS_2089
   DS2089
   ISO646-DK
   dk
*/

static DOUBLE_TABLE table_71 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z AEO/AA'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z aeo/aa'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* us-dk
*/

static DOUBLE_TABLE table_72 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* dk-us
*/

static DOUBLE_TABLE table_73 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z AEO/AA'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z aeo/aa'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* JIS_X0201
   X0201
*/

static DOUBLE_TABLE table_74 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(Ye)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'-DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NS._<'>',_.6Woa6i6u6e6o6YAYUYOTU-6A6I6U6E6O6KaKiKuKeKoSaSiSuSeSo",
    "TaTiTuTeToNaNiNuNeNoHaHiHuHeHoMaMiMuMeMoYaYuYoRaRiRuReRoWaN6\"505",
    NULL,
  };

/* KSC5636
   ISO646-KR
*/

static DOUBLE_TABLE table_75 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(W=)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    NULL,
    NULL,
    NULL,
    NULL,
  };

/* DEC-MCS
   dec
*/

static DOUBLE_TABLE table_76 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "  !ICtPd  Ye  SECuCo-a<<        DG+-2S3S  MyPI.M  1S-o>>1412  ?I",
    "A!A'A>A?A:AAAEC,E!E'E>E:I!I'I>I:  N?O!O'O>O?O:OEO/U!U'U>U:Y:  ss",
    "a!a'a>a?a:aaaec,e!e'e>e:i!i'i>i:  n?o!o'o>o?o:oeo/u!u'u>u:y:    ",
  };

/* hp-roman8
   roman8
   r8
*/

static DOUBLE_TABLE table_77 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "PAHOBHNHINNLSAESHSHJVSPDPURIS2S3DCP1P2TSCCMWSGEGSSGCSCCISTOCPMAC",
    "NSA!A>E!E>E:I>I:''1\"AN':?1U!U>Li'-Y'y'DGC,c,N?n?!I?ICuPdYeSEFlCt",
    "a>e>o>u>a'e'o'u'a!e!o!u!a:e:o:u:AAi>O/AEaai'o/aeA:i!O:U:E'i:ssO>",
    "A'A?a?D-d-I'I!O'O!O?o?S<s<U'Y:y:THth.MMyPI34-M1412-a-o<<fS>>+-  ",
  };

/* macintosh
   mac
*/

static DOUBLE_TABLE table_78 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    "SP! \" NbDO% & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? ",
    "AtA B C D E F G H I J K L M N O P Q R S T U V W X Y Z <(//)>'>_ ",
    "'!a b c d e f g h i j k l m n o p q r s t u v w x y z (!!!!)'?DT",
    "A:AAC,E'N?O:U:a'a!a>a:a?aac,e'e!e>e:i'i!i>i:n?o'o!o>o:o?u'u!u>u:",
    "/-DGCtPdSESbPIssRgCoTM''':!=AEO/00+-=<>=YeMydP+Z*Pp*In-a-oW*aeo/",
    "?I!INORTFl?2D*<<>>.3NSA!A?O?OEoe-M-N\"6\"9'6'9-:Dby:Y:/fCu<1>1fifl",
    "/=.M.9:9%0A>E>A'E:E!I'I>I:I!O'O>  O!U'U>U!i.    '-'('.'0','\"';'<",
  };

/* IBM037
   cp037
   ebcdic-cp-us
   ebcdic-cp-ca
   ebcdic-cp-wt
   ebcdic-cp-nl
*/

static DOUBLE_TABLE table_79 = 
  {
    "NUSHSXEXETEQAKBLBSHTLFVTFFCRSOSIDLD1D2D3D4NKSYEBCNEMSBECFSGSRSUS",
    NULL,
    "SPNSa>a:a!a'a?aac,n?Ct. < ( + !!& e'e>e:e!i'i>i:i!ss! DO* ) ; NO",
    "- / A>A:A!A'A?AAC,N?BB, % _ > ? o/E'E>E:E!I'I>I:I!'!: NbAt' = \" ",
    "O/a b c d e f g h i <<>>d-y'th+-DGj k l m n o p q r -a-oae',AECu",
    "My'?s t u v w x y z !I?ID-Y'THRg'>PdYe.MCoSEPI141234<()>'-':''*X",
    "(!A B C D E F G H I --o>o:o!o'o?!)J K L M N O P Q R 1Su>u:u!u'y:",
    "//-:S T U V W X Y Z 2SO>O:O!O'O?0 1 2 3 4 5 6 7 8 9 3SU>U:U!U'DT",
  };

void
module_charset1 (void)
{
  declare_double_step (&table_0, "ISO_646.basic:1983", 2);
  declare_double_step (&table_1, "INVARIANT", 2);
  declare_double_step (&table_2, "ISO_646.irv:1983", 2);
  declare_double_step (&table_3, "BS_4730", 2);
  declare_double_step (&table_4, "ANSI_X3.4-1968", 2);
  declare_double_step (&table_5, "NATS-SEFI", 2);
  declare_double_step (&table_6, "NATS-SEFI-ADD", 2);
  declare_double_step (&table_7, "NATS-DANO", 2);
  declare_double_step (&table_8, "NATS-DANO-ADD", 2);
  declare_double_step (&table_9, "SEN_850200_B", 2);
  declare_double_step (&table_10, "SEN_850200_C", 2);
  declare_double_step (&table_11, "JIS_C6220-1969-jp", 2);
  declare_double_step (&table_12, "JIS_C6220-1969-ro", 2);
  declare_double_step (&table_13, "IT", 2);
  declare_double_step (&table_14, "PT", 2);
  declare_double_step (&table_15, "ES", 2);
  declare_double_step (&table_16, "greek7-old", 2);
  declare_double_step (&table_17, "latin-greek", 2);
  declare_double_step (&table_18, "DIN_66003", 2);
  declare_double_step (&table_19, "NF_Z_62-010_(1973)", 2);
  declare_double_step (&table_20, "Latin-greek-1", 2);
  declare_double_step (&table_21, "ISO_5427", 2);
  declare_double_step (&table_22, "BS_viewdata", 2);
  declare_double_step (&table_23, "INIS", 2);
  declare_double_step (&table_24, "INIS-8", 2);
  declare_double_step (&table_25, "INIS-cyrillic", 2);
  declare_double_step (&table_26, "ISO_5427:1981", 2);
  declare_double_step (&table_27, "ISO_5428:1980", 2);
  declare_double_step (&table_28, "GB_1988-80", 2);
  declare_double_step (&table_29, "NS_4551-1", 2);
  declare_double_step (&table_30, "NS_4551-2", 2);
  declare_double_step (&table_31, "NF_Z_62-010", 2);
  declare_double_step (&table_32, "PT2", 2);
  declare_double_step (&table_33, "ES2", 2);
  declare_double_step (&table_34, "MSZ_7795.3", 2);
  declare_double_step (&table_35, "greek7", 2);
  declare_double_step (&table_36, "ASMO_449", 2);
  declare_double_step (&table_37, "JIS_C6229-1984-a", 2);
  declare_double_step (&table_38, "JIS_C6229-1984-b", 2);
  declare_double_step (&table_39, "JIS_C6229-1984-b-add", 2);
  declare_double_step (&table_40, "JIS_C6229-1984-hand", 2);
  declare_double_step (&table_41, "JIS_C6229-1984-hand-add", 2);
  declare_double_step (&table_42, "JIS_C6229-1984-kana", 2);
  declare_double_step (&table_43, "ISO_2033-1983", 2);
  declare_double_step (&table_44, "ISO_8859-1:1987", 2);
  declare_double_step (&table_45, "ISO_8859-2:1987", 2);
  declare_double_step (&table_46, "T.61-7bit", 2);
  declare_double_step (&table_47, "ISO_8859-3:1988", 2);
  declare_double_step (&table_48, "ISO_8859-4:1988", 2);
  declare_double_step (&table_49, "ECMA-cyrillic", 2);
  declare_double_step (&table_50, "CSA_Z243.4-1985-1", 2);
  declare_double_step (&table_51, "CSA_Z243.4-1985-2", 2);
  declare_double_step (&table_52, "CSA_Z243.4-1985-gr", 2);
  declare_double_step (&table_53, "ISO_8859-7:1987", 2);
  declare_double_step (&table_54, "ISO_8859-6:1987", 2);
  declare_double_step (&table_55, "ISO_8859-8:1988", 2);
  declare_double_step (&table_56, "CSN_369103", 2);
  declare_double_step (&table_57, "JUS_I.B1.002", 2);
  declare_double_step (&table_58, "IEC_P27-1", 2);
  declare_double_step (&table_59, "ISO_8859-5:1988", 2);
  declare_double_step (&table_60, "JUS_I.B1.003-serb", 2);
  declare_double_step (&table_61, "JUS_I.B1.003-mac", 2);
  declare_double_step (&table_62, "ISO_8859-9:1989", 2);
  declare_double_step (&table_63, "greek-ccitt", 2);
  declare_double_step (&table_64, "NC_NC00-10:81", 2);
  declare_double_step (&table_65, "ISO_6937-2-25", 2);
  declare_double_step (&table_66, "GOST_19768-74", 2);
  declare_double_step (&table_67, "ISO_8859-supp", 2);
  declare_double_step (&table_68, "ISO_10367-box", 2);
  declare_double_step (&table_69, "latin6", 2);
  declare_double_step (&table_70, "latin-lap", 2);
  declare_double_step (&table_71, "DS_2089", 2);
  declare_double_step (&table_72, "us-dk", 2);
  declare_double_step (&table_73, "dk-us", 2);
  declare_double_step (&table_74, "JIS_X0201", 2);
  declare_double_step (&table_75, "KSC5636", 2);
  declare_double_step (&table_76, "DEC-MCS", 2);
  declare_double_step (&table_77, "hp-roman8", 2);
  declare_double_step (&table_78, "macintosh", 2);
  declare_double_step (&table_79, "IBM037", 2);

  declare_alias ("ref", "ISO_646.basic:1983");
  declare_alias ("iso-ir-2", "ISO_646.irv:1983");
  declare_alias ("irv", "ISO_646.irv:1983");
  declare_alias ("iso-ir-4", "BS_4730");
  declare_alias ("ISO646-GB", "BS_4730");
  declare_alias ("gb", "BS_4730");
  declare_alias ("uk", "BS_4730");
  declare_alias ("iso-ir-6", "ANSI_X3.4-1968");
  declare_alias ("ANSI_X3.4-1986", "ANSI_X3.4-1968");
  declare_alias ("ISO_646.irv:1991", "ANSI_X3.4-1968");
  declare_alias ("ASCII", "ANSI_X3.4-1968");
  declare_alias ("ISO646-US", "ANSI_X3.4-1968");
  declare_alias ("US-ASCII", "ANSI_X3.4-1968");
  declare_alias ("us", "ANSI_X3.4-1968");
  declare_alias ("IBM367", "ANSI_X3.4-1968");
  declare_alias ("cp367", "ANSI_X3.4-1968");
  declare_alias ("iso-ir-8-1", "NATS-SEFI");
  declare_alias ("iso-ir-8-2", "NATS-SEFI-ADD");
  declare_alias ("iso-ir-9-1", "NATS-DANO");
  declare_alias ("iso-ir-9-2", "NATS-DANO-ADD");
  declare_alias ("iso-ir-10", "SEN_850200_B");
  declare_alias ("FI", "SEN_850200_B");
  declare_alias ("ISO646-FI", "SEN_850200_B");
  declare_alias ("ISO646-SE", "SEN_850200_B");
  declare_alias ("se", "SEN_850200_B");
  declare_alias ("iso-ir-11", "SEN_850200_C");
  declare_alias ("ISO646-SE2", "SEN_850200_C");
  declare_alias ("se2", "SEN_850200_C");
  declare_alias ("JIS_C6220-1969", "JIS_C6220-1969-jp");
  declare_alias ("iso-ir-13", "JIS_C6220-1969-jp");
  declare_alias ("katakana", "JIS_C6220-1969-jp");
  declare_alias ("x0201-7", "JIS_C6220-1969-jp");
  declare_alias ("iso-ir-14", "JIS_C6220-1969-ro");
  declare_alias ("jp", "JIS_C6220-1969-ro");
  declare_alias ("ISO646-JP", "JIS_C6220-1969-ro");
  declare_alias ("iso-ir-15", "IT");
  declare_alias ("ISO646-IT", "IT");
  declare_alias ("iso-ir-16", "PT");
  declare_alias ("ISO646-PT", "PT");
  declare_alias ("iso-ir-17", "ES");
  declare_alias ("ISO646-ES", "ES");
  declare_alias ("iso-ir-18", "greek7-old");
  declare_alias ("iso-ir-19", "latin-greek");
  declare_alias ("iso-ir-21", "DIN_66003");
  declare_alias ("de", "DIN_66003");
  declare_alias ("ISO646-DE", "DIN_66003");
  declare_alias ("iso-ir-25", "NF_Z_62-010_(1973)");
  declare_alias ("ISO646-FR1", "NF_Z_62-010_(1973)");
  declare_alias ("iso-ir-27", "Latin-greek-1");
  declare_alias ("iso-ir-37", "ISO_5427");
  declare_alias ("iso-ir-47", "BS_viewdata");
  declare_alias ("iso-ir-49", "INIS");
  declare_alias ("iso-ir-50", "INIS-8");
  declare_alias ("iso-ir-51", "INIS-cyrillic");
  declare_alias ("iso-ir-54", "ISO_5427:1981");
  declare_alias ("iso-ir-55", "ISO_5428:1980");
  declare_alias ("iso-ir-57", "GB_1988-80");
  declare_alias ("cn", "GB_1988-80");
  declare_alias ("ISO646-CN", "GB_1988-80");
  declare_alias ("iso-ir-60", "NS_4551-1");
  declare_alias ("ISO646-NO", "NS_4551-1");
  declare_alias ("no", "NS_4551-1");
  declare_alias ("ISO646-NO2", "NS_4551-2");
  declare_alias ("iso-ir-61", "NS_4551-2");
  declare_alias ("no2", "NS_4551-2");
  declare_alias ("iso-ir-69", "NF_Z_62-010");
  declare_alias ("ISO646-FR", "NF_Z_62-010");
  declare_alias ("fr", "NF_Z_62-010");
  declare_alias ("iso-ir-84", "PT2");
  declare_alias ("ISO646-PT2", "PT2");
  declare_alias ("iso-ir-85", "ES2");
  declare_alias ("ISO646-ES2", "ES2");
  declare_alias ("iso-ir-86", "MSZ_7795.3");
  declare_alias ("ISO646-HU", "MSZ_7795.3");
  declare_alias ("hu", "MSZ_7795.3");
  declare_alias ("iso-ir-88", "greek7");
  declare_alias ("ISO_9036", "ASMO_449");
  declare_alias ("arabic7", "ASMO_449");
  declare_alias ("iso-ir-89", "ASMO_449");
  declare_alias ("jp-ocr-a", "JIS_C6229-1984-a");
  declare_alias ("ISO646-JP-OCR-B", "JIS_C6229-1984-b");
  declare_alias ("jp-ocr-b", "JIS_C6229-1984-b");
  declare_alias ("iso-ir-93", "JIS_C6229-1984-b-add");
  declare_alias ("jp-ocr-b-add", "JIS_C6229-1984-b-add");
  declare_alias ("iso-ir-94", "JIS_C6229-1984-hand");
  declare_alias ("jp-ocr-hand", "JIS_C6229-1984-hand");
  declare_alias ("iso-ir-95", "JIS_C6229-1984-hand-add");
  declare_alias ("jp-ocr-hand-add", "JIS_C6229-1984-hand-add");
  declare_alias ("iso-ir-96", "JIS_C6229-1984-kana");
  declare_alias ("iso-ir-98", "ISO_2033-1983");
  declare_alias ("e13b", "ISO_2033-1983");
  declare_alias ("iso-ir-100", "ISO_8859-1:1987");
  declare_alias ("ISO_8859-1", "ISO_8859-1:1987");
  declare_alias ("ISO-8859-1", "ISO_8859-1:1987");
  declare_alias ("latin1", "ISO_8859-1:1987");
  declare_alias ("l1", "ISO_8859-1:1987");
  declare_alias ("IBM819", "ISO_8859-1:1987");
  declare_alias ("CP819", "ISO_8859-1:1987");
  declare_alias ("iso-ir-101", "ISO_8859-2:1987");
  declare_alias ("ISO_8859-2", "ISO_8859-2:1987");
  declare_alias ("ISO-8859-2", "ISO_8859-2:1987");
  declare_alias ("latin2", "ISO_8859-2:1987");
  declare_alias ("l2", "ISO_8859-2:1987");
  declare_alias ("iso-ir-102", "T.61-7bit");
  declare_alias ("iso-ir-109", "ISO_8859-3:1988");
  declare_alias ("ISO_8859-3", "ISO_8859-3:1988");
  declare_alias ("ISO-8859-3", "ISO_8859-3:1988");
  declare_alias ("latin3", "ISO_8859-3:1988");
  declare_alias ("l3", "ISO_8859-3:1988");
  declare_alias ("iso-ir-110", "ISO_8859-4:1988");
  declare_alias ("ISO_8859-4", "ISO_8859-4:1988");
  declare_alias ("ISO-8859-4", "ISO_8859-4:1988");
  declare_alias ("latin4", "ISO_8859-4:1988");
  declare_alias ("l4", "ISO_8859-4:1988");
  declare_alias ("iso-ir-111", "ECMA-cyrillic");
  declare_alias ("iso-ir-121", "CSA_Z243.4-1985-1");
  declare_alias ("ISO646-CA", "CSA_Z243.4-1985-1");
  declare_alias ("csa7-1", "CSA_Z243.4-1985-1");
  declare_alias ("ca", "CSA_Z243.4-1985-1");
  declare_alias ("iso-ir-122", "CSA_Z243.4-1985-2");
  declare_alias ("ISO646-CA2", "CSA_Z243.4-1985-2");
  declare_alias ("csa7-2", "CSA_Z243.4-1985-2");
  declare_alias ("iso-ir-123", "CSA_Z243.4-1985-gr");
  declare_alias ("iso-ir-126", "ISO_8859-7:1987");
  declare_alias ("ISO_8859-7", "ISO_8859-7:1987");
  declare_alias ("ISO-8859-7", "ISO_8859-7:1987");
  declare_alias ("ELOT_928", "ISO_8859-7:1987");
  declare_alias ("ECMA-118", "ISO_8859-7:1987");
  declare_alias ("greek", "ISO_8859-7:1987");
  declare_alias ("greek8", "ISO_8859-7:1987");
  declare_alias ("iso-ir-127", "ISO_8859-6:1987");
  declare_alias ("ISO_8859-6", "ISO_8859-6:1987");
  declare_alias ("ISO-8859-6", "ISO_8859-6:1987");
  declare_alias ("ECMA-114", "ISO_8859-6:1987");
  declare_alias ("ASMO-708", "ISO_8859-6:1987");
  declare_alias ("arabic", "ISO_8859-6:1987");
  declare_alias ("iso-ir-138", "ISO_8859-8:1988");
  declare_alias ("ISO_8859-8", "ISO_8859-8:1988");
  declare_alias ("ISO-8859-8", "ISO_8859-8:1988");
  declare_alias ("hebrew", "ISO_8859-8:1988");
  declare_alias ("iso-ir-139", "CSN_369103");
  declare_alias ("iso-ir-141", "JUS_I.B1.002");
  declare_alias ("ISO646-YU", "JUS_I.B1.002");
  declare_alias ("js", "JUS_I.B1.002");
  declare_alias ("yu", "JUS_I.B1.002");
  declare_alias ("iso-ir-143", "IEC_P27-1");
  declare_alias ("iso-ir-144", "ISO_8859-5:1988");
  declare_alias ("ISO_8859-5", "ISO_8859-5:1988");
  declare_alias ("ISO-8859-5", "ISO_8859-5:1988");
  declare_alias ("cyrillic", "ISO_8859-5:1988");
  declare_alias ("iso-ir-146", "JUS_I.B1.003-serb");
  declare_alias ("serbian", "JUS_I.B1.003-serb");
  declare_alias ("macedonian", "JUS_I.B1.003-mac");
  declare_alias ("iso-ir-147", "JUS_I.B1.003-mac");
  declare_alias ("iso-ir-148", "ISO_8859-9:1989");
  declare_alias ("ISO_8859-9", "ISO_8859-9:1989");
  declare_alias ("ISO-8859-9", "ISO_8859-9:1989");
  declare_alias ("latin5", "ISO_8859-9:1989");
  declare_alias ("l5", "ISO_8859-9:1989");
  declare_alias ("iso-ir-150", "greek-ccitt");
  declare_alias ("cuba", "NC_NC00-10:81");
  declare_alias ("iso-ir-151", "NC_NC00-10:81");
  declare_alias ("ISO646-CU", "NC_NC00-10:81");
  declare_alias ("iso-ir-152", "ISO_6937-2-25");
  declare_alias ("ST_SEV_358-88", "GOST_19768-74");
  declare_alias ("iso-ir-153", "GOST_19768-74");
  declare_alias ("iso-ir-154", "ISO_8859-supp");
  declare_alias ("latin1-2-5", "ISO_8859-supp");
  declare_alias ("iso-ir-155", "ISO_10367-box");
  declare_alias ("iso-ir-157", "latin6");
  declare_alias ("l6", "latin6");
  declare_alias ("lap", "latin-lap");
  declare_alias ("iso-ir-158", "latin-lap");
  declare_alias ("DS2089", "DS_2089");
  declare_alias ("ISO646-DK", "DS_2089");
  declare_alias ("dk", "DS_2089");
  declare_alias ("X0201", "JIS_X0201");
  declare_alias ("ISO646-KR", "KSC5636");
  declare_alias ("dec", "DEC-MCS");
  declare_alias ("roman8", "hp-roman8");
  declare_alias ("r8", "hp-roman8");
  declare_alias ("mac", "macintosh");
  declare_alias ("cp037", "IBM037");
  declare_alias ("ebcdic-cp-us", "IBM037");
  declare_alias ("ebcdic-cp-ca", "IBM037");
  declare_alias ("ebcdic-cp-wt", "IBM037");
  declare_alias ("ebcdic-cp-nl", "IBM037");
  declare_alias ("EBCDIC-INT", "IBM038");
  declare_alias ("cp038", "IBM038");
}
