#!/bin/sh
# Execute a suite made up of one, or only a few `m4' files.
# Copyright © 1998 Progiciels Bourbeau-Pinard inc.
# François Pinard <pinard@iro.umontreal.ca>, 1998.

if test -f atconfig; then
  . ./atconfig
else
  echo >&2 'Execute from the testing directory in the build hierarchy.'
  echo >&2 '  (a typical call is: ../../tests/test-one t-exclude.m4).'
  exit 1
fi

grep AT_INIT $at_srcdir/suite.m4 \
| m4 -I $at_srcdir atgeneral.m4 - $* | cat -s > one

sh one
