/* Automatically generated by po2tbl.sed from recode.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
UCS2   Mne   Description\n\
\n", 2},
  {"No error", 3},
  {"Non canonical input", 4},
  {"Ambiguous output", 5},
  {"Untranslatable input", 6},
  {"Invalid input", 7},
  {"System detected problem", 8},
  {"Misuse of recoding library", 9},
  {"Internal recoding bug", 10},
  {"\
This program is free software; you can redistribute it and/or modify\n\
it under the terms of the GNU General Public License as published by\n\
the Free Software Foundation; either version 2, or (at your option)\n\
any later version.\n\
\n\
This program is distributed in the hope that it will be useful,\n\
but WITHOUT ANY WARRANTY; without even the implied warranty of\n\
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n\
GNU General Public License for more details.\n\
\n\
You should have received a copy of the GNU General Public License\n\
along with this program; if not, write to the Free Software Foundation,\n\
Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.\n", 11},
  {"Try `%s %s' for more information.\n", 12},
  {"\
Free `recode' converts files between various character sets and surfaces.\n", 13},
  {"\
\n\
Usage: %s [OPTION]... [ [CHARSET] | REQUEST [FILE]... ]\n", 14},
  {"\
\n\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.  Similarly for optional arguments.\n", 15},
  {"\
\n\
Listings:\n\
  -l, --list[=FORMAT]        list one or all known charsets\n\
  -k, --known=PAIRS          restrict charsets according to known PAIRS \
list\n\
  -h, --header[=[LN/]NAME]   write table NAME on stdout using LN, then exit\n\
  -F, --freeze-tables        write out a C module holding all tables\n\
  -T, --find-subsets         report all charsets being subset of others\n\
  -C, --copyright            display Copyright and copying conditions\n\
      --help                 display this help and exit\n\
      --version              output version information and exit\n", 16},
  {"\
\n\
Operation modes:\n\
  -v, --verbose           explain sequence of steps and report progress\n\
  -q, --quiet, --silent   inhibit messages about irreversible recodings\n\
  -f, --force             force recodings even when not reversible\n\
  -t, --touch             touch the recoded files after replacement\n\
  -i, --sequence=files    use intermediate files for sequencing passes\n\
      --sequence=memory   use memory buffers for sequencing passes\n", 17},
  {"  -p, --sequence=pipe     use pipe machinery for sequencing passes\n", 18},
  {"  -p, --sequence=pipe     same as -i (on this system)\n", 19},
  {"\
\n\
Fine tuning:\n\
  -s, --strict           use strict mappings, even loose characters\n\
  -d, --diacritics       convert only diacritics or alike for HTML/LaTeX\n\
  -S, --source[=LN]      limit recoding to strings and comments as for LN\n\
  -c, --colons           use colons instead of double quotes for diaeresis\n\
  -g, --graphics         approximate IBMPC rulers by ASCII graphics\n\
  -x, --ignore=CHARSET   ignore CHARSET while choosing a recoding path\n", 20},
  {"\
\n\
Option -l with no FORMAT nor CHARSET list available charsets and surfaces.\n\
FORMAT is `decimal', `octal', `hexadecimal' or `full' (or one of `dohf').\n", 21},
  {"\
Unless DEFAULT_CHARSET is set in environment, CHARSET defaults to `%s'.\n", 22},
  {"CHARSET has no default, define DEFAULT_CHARSET in the environment.\n", 23},
  {"\
With -k, possible before charsets are listed for the given after CHARSET,\n\
both being tabular charsets, with PAIRS of the form \
`BEF1:AFT1,BEF2:AFT2,...'\n\
and BEFs and AFTs being codes are given as decimal numbers.\n", 24},
  {"\
LN is some language, it may be `c', `perl' or `po'; `c' is the default.\n", 25},
  {"\
\n\
REQUEST is SUBREQUEST[,SUBREQUEST]...; SUBREQUEST is \
ENCODING[..ENCODING]...\n\
ENCODING is [CHARSET][/[SURFACE]]...; REQUEST often looks like \
BEFORE..AFTER,\n\
with BEFORE and AFTER being charsets.  An omitted CHARSET implies the usual\n\
charset; an omitted [/SURFACE]... means the implied surfaces for CHARSET; a \
/\n\
with an empty surface name means no surfaces at all.  See the manual.\n", 26},
  {"\
\n\
If none of -i and -p are given, presume -p if no FILE, else -i.\n\
Each FILE is recoded over itself, destroying the original.  If no\n\
FILE is specified, then act as a filter and recode stdin to stdout.\n", 27},
  {"\
\n\
Report bugs to <recode-bugs@iro.umontreal.ca>.\n", 28},
  {"Ambiguous sequence `%s'", 29},
  {"Unknown sequence `%s'", 30},
  {"Ambiguous language `%s'", 31},
  {"Unknown language `%s'", 32},
  {"Ambiguous format `%s'", 33},
  {"Unknown format `%s'", 34},
  {"\
\n\
Copyright (C) 1990, 92, 93, 94, 96, 97, 99 Free Software Foundation, Inc.\n", 35},
  {"\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n", 36},
  {"\
\n\
Written by Franc,ois Pinard <pinard@iro.umontreal.ca>.\n", 37},
  {"Deprecated syntax, please prefer `%s'", 38},
  {"Erroneous request `%s'", 39},
  {"Recoding %s...", 40},
  {" done\n", 41},
  {" failed: %s in %s..%s\n", 42},
  {"%s failed: %s in %s..%s", 43},
  {"%s in %s..%s", 44},
  {"Charset %s already exists and is not %s", 45},
  {"Cannot list `%s', no names available for this charset", 46},
  {"Dec  Oct Hex   UCS2  Mne  %s\n", 47},
  {"Sorry, no names available for `%s'", 48},
  {"Resurfacer set more than once for `%s'", 49},
  {"Unsurfacer set more than once for `%s'", 50},
  {"Virtual memory exhausted", 51},
  {"Codes %3d and %3d both recode to %3d", 52},
  {"No character recodes to %3d", 53},
  {"Cannot invert given one-to-one table", 54},
  {"Following diagnostics for `%s' to `%s'", 55},
  {"Pair no. %d: <%3d, %3d> conflicts with <%3d, %3d>", 56},
  {"Cannot complete table from set of known pairs", 57},
  {"Identity recoding, not worth a table", 58},
  {"Recoding is too complex for a mere table", 59},
  {"%sConversion table generated mechanically by Free `%s' %s", 60},
  {"%sfor sequence %s.%s", 61},
  {"No table to print", 62},
  {"reversible", 63},
  {"%s to %s", 64},
  {"byte", 65},
  {"ucs2", 66},
  {"variable", 67},
  {"*Unachievable*", 68},
  {"*mere copy*", 69},
  {"Virtual memory exhausted!", 70},
  {"Step initialisation failed", 71},
  {"Step initialisation failed (unprocessed options)", 72},
  {"Request: %s\n", 73},
  {"Shrunk to: %s\n", 74},
  {"Unrecognised surface name `%s'", 75},
  {"No way to recode from `%s' to `%s'", 76},
  {"Expecting `..' in request", 77},
  {"Child process wait status is 0x%0.2x", 78},
};

int _msg_tbl_length = 78;
