/* DO NOT MODIFY THIS FILE!  It was generated by `recode/doc/tables.py'.  */

/* Conversion of files between different charsets and surfaces.
   Copyright © 1999 Free Software Foundation, Inc.
   Contributed by François Pinard <pinard@iro.umontreal.ca>, 1993, 1997.

   The `recode' Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public License
   as published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   The `recode' Library is distributed in the hope that it will be
   useful, but WITHOUT ANY WARRANTY; without even the implied warranty
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public
   License along with the `recode' Library; see the file `COPYING.LIB'.
   If not, write to the Free Software Foundation, Inc., 59 Temple Place -
   Suite 330, Boston, MA 02111-1307, USA.  */

/* This is derived from Bruno Haible's `libiconv' package.  */
static const char *iconv_name_list[350] =
  {
    "US-ASCII",
	"ASCII",
	"ISO646-US",
	"ISO_646.IRV:1991",
	"ISO-IR-6",
	"ANSI_X3.4-1968",
	"CP367",
	"IBM367",
	"US",
	"CSASCII", NULL,

    /* General multi-byte encodings.  */

    "UTF-8", NULL,
    "UCS-2",
	"ISO-10646-UCS-2",
	"CSUNICODE", NULL,
    "UCS-4",
	"ISO-10646-UCS-4",
	"CSUCS4", NULL,
    "UTF-16", NULL,
    "UTF-7",
	"UNICODE-1-1-UTF-7",
	"CSUNICODE11UTF7", NULL,
    "UCS-2-INTERNAL", NULL,
    "UCS-2-SWAPPED", NULL,
    "UCS-2-BE",
	"UNICODEBIG", NULL,
    "UCS-2-LE",
	"UNICODELITTLE", NULL,
    "UCS-4-INTERNAL", NULL,
    "UCS-4-SWAPPED", NULL,
    "UCS-4-BE", NULL,
    "UCS-4-LE", NULL,
    "JAVA", NULL,

    /* Standard 8-bit encodings.  */

    "ISO-8859-1",
	"ISO_8859-1",
	"ISO_8859-1:1987",
	"ISO-IR-100",
	"CP819",
	"IBM819",
	"LATIN1",
	"L1",
	"CSISOLATIN1", NULL,
    "ISO-8859-2",
	"ISO_8859-2",
	"ISO_8859-2:1987",
	"ISO-IR-101",
	"LATIN2",
	"L2",
	"CSISOLATIN2", NULL,
    "ISO-8859-3",
	"ISO_8859-3",
	"ISO_8859-3:1988",
	"ISO-IR-109",
	"LATIN3",
	"L3",
	"CSISOLATIN3", NULL,
    "ISO-8859-4",
	"ISO_8859-4",
	"ISO_8859-4:1988",
	"ISO-IR-110",
	"LATIN4",
	"L4",
	"CSISOLATIN4", NULL,
    "ISO-8859-5",
	"ISO_8859-5",
	"ISO_8859-5:1988",
	"ISO-IR-144",
	"CYRILLIC",
	"CSISOLATINCYRILLIC", NULL,
    "ISO-8859-6",
	"ISO_8859-6",
	"ISO_8859-6:1987",
	"ISO-IR-127",
	"ECMA-114",
	"ASMO-708",
	"ARABIC",
	"CSISOLATINARABIC", NULL,
    "ISO-8859-7",
	"ISO_8859-7",
	"ISO_8859-7:1987",
	"ISO-IR-126",
	"ECMA-118",
	"ELOT_928",
	"GREEK8",
	"GREEK",
	"CSISOLATINGREEK", NULL,
    "ISO-8859-8",
	"ISO_8859-8",
	"ISO_8859-8:1988",
	"ISO-IR-138",
	"HEBREW",
	"CSISOLATINHEBREW", NULL,
    "ISO-8859-9",
	"ISO_8859-9",
	"ISO_8859-9:1989",
	"ISO-IR-148",
	"LATIN5",
	"L5",
	"CSISOLATIN5", NULL,
    "ISO-8859-10",
	"ISO_8859-10",
	"ISO_8859-10:1992",
	"ISO-IR-157",
	"LATIN6",
	"L6",
	"CSISOLATIN6", NULL,
    "ISO-8859-13",
	"ISO_8859-13",
	"ISO-IR-179",
	"LATIN7",
	"L7", NULL,
    "ISO-8859-14",
	"ISO_8859-14",
	"ISO_8859-14:1998",
	"LATIN8",
	"L8", NULL,
    "ISO-8859-15",
	"ISO_8859-15",
	"ISO_8859-15:1998", NULL,
    "KOI8-R",
	"CSKOI8R", NULL,
    "KOI8-U", NULL,
    "KOI8-RU", NULL,

    /* Windows 8-bit encodings.  */

    "CP1250",
	"WINDOWS-1250",
	"MS-EE", NULL,
    "CP1251",
	"WINDOWS-1251",
	"MS-CYRL", NULL,
    "CP1252",
	"WINDOWS-1252",
	"MS-ANSI", NULL,
    "CP1253",
	"WINDOWS-1253",
	"MS-GREEK", NULL,
    "CP1254",
	"WINDOWS-1254",
	"MS-TURK", NULL,
    "CP1255",
	"WINDOWS-1255",
	"MS-HEBR", NULL,
    "CP1256",
	"WINDOWS-1256",
	"MS-ARAB", NULL,
    "CP1257",
	"WINDOWS-1257",
	"WINBALTRIM", NULL,
    "CP1258",
	"WINDOWS-1258", NULL,

    /* DOS 8-bit encodings.  */

    "CP850",
	"IBM850",
	"850",
	"CSPC850MULTILINGUAL", NULL,
    "CP866",
	"IBM866",
	"866",
	"CSIBM866", NULL,

    /* Macintosh 8-bit encodings.  */

    "MacRoman",
	"Macintosh", NULL,
    "MacCentralEurope", NULL,
    "MacIceland", NULL,
    "MacCroatian", NULL,
    "MacRomania", NULL,
    "MacCyrillic", NULL,
    "MacUkraine", NULL,
    "MacGreek", NULL,
    "MacTurkish", NULL,
    "MacHebrew", NULL,
    "MacArabic", NULL,
    "MacThai", NULL,

    /* Other platform specific 8-bit encodings.  */

    "HP-ROMAN8",
	"ROMAN8",
	"R8",
	"CSHPROMAN8", NULL,
    "NEXTSTEP", NULL,

    /* Regional 8-bit encodings used for a single language.  */

    "ARMSCII-8", NULL,
    "Georgian-Academy", NULL,
    "Georgian-PS", NULL,
    "MuleLao-1", NULL,
    "CP1133",
	"IBM-CP1133", NULL,
    "TIS-620",
	"TIS620",
	"TIS620-0",
	"TIS620.2529-1",
	"TIS620.2533-0",
	"TIS620.2533-1",
	"ISO-IR-166", NULL,
    "CP874",
	"WINDOWS-874", NULL,
    "VISCII",
	"VISCII1.1-1",
	"CSVISCII", NULL,
    "TCVN",
	"TCVN-5712",
	"TCVN5712-1",
	"TCVN5712-1:1993", NULL,

    /* CJK character sets.  */

    "JIS_X0201",
	"JISX0201-1976",
	"JISX0201.1976-0",
	"X0201",
	"CSHALFWIDTHKATAKANA", NULL,
    "JIS_X0208",
	"JIS_X0208.1983-0",
	"JIS_X0208.1983-1",
	"JIS_X0208-1983",
	"JIS_X0208-1990",
	"JIS0208", NULL,
    "JIS_X0212",
	"JIS_X0212.1990-0",
	"JIS_X0212-1990",
	"X0212",
	"ISO-IR-159",
	"CSISO159JISX02121990", NULL,
    "KSC_5601",
	"KSC5601.1987-0",
	"KS_C_5601-1987",
	"KS_C_5601-1989",
	"ISO-IR-149",
	"CSKSC56011987",
	"KOREAN",
	"CP949", NULL,

    /* CJK encodings.  */

    "EUC-JP",
	"EUCJP",
	"EXTENDED_UNIX_CODE_PACKED_FORMAT_FOR_JAPANESE",
	"CSEUCPKDFMTJAPANESE", NULL,
    "SJIS",
	"SHIFT_JIS",
	"SHIFT-JIS",
	"MS_KANJI",
	"CSSHIFTJIS", NULL,
    "CP932", NULL,
    "ISO-2022-JP",
	"CSISO2022JP", NULL,
    "ISO-2022-JP-1", NULL,
    "ISO-2022-JP-2",
	"CSISO2022JP2", NULL,
    "EUC-CN",
	"EUCCN",
	"GB2312",
	"CSGB2312", NULL,
    "GBK",
	"CP936", NULL,
    "ISO-2022-CN",
	"CSISO2022CN", NULL,
    "ISO-2022-CN-EXT", NULL,
    "HZ",
	"HZ-GB-2312", NULL,
    "EUC-TW",
	"EUCTW",
	"CSEUCTW", NULL,
    "BIG5",
	"BIG-5",
	"BIG-FIVE",
	"BIGFIVE",
	"CSBIG5", NULL,
    "CP950", NULL,
    "EUC-KR",
	"EUCKR",
	"CSEUCKR", NULL,
    "JOHAB",
	"CP1361", NULL,
    "ISO-2022-KR",
	"CSISO2022KR", NULL,
    NULL
  };

typedef void *iconv_t;
#ifndef EILSEQ
# define EILSEQ EINVAL
#endif

#ifdef __cplusplus
extern "C" {
#endif

iconv_t iconv_open (const char *, const char *);
size_t iconv (iconv_t, const char **, size_t *, char **, size_t *);
extern int iconv_close (iconv_t cd);

#ifdef __cplusplus
}
#endif
